#!/bin/bash

docker compose build --no-cache && docker compose up -d \
   && docker tag facebook_leads-app:latest delciocapolo/facebook_leads:v1.0 \
   && docker push delciocapolo/facebook_leads:v1.0 \
